const e=require('express'),h=require('http'),{Server:S}=require('socket.io'),a=e(),s=h.createServer(a),io=new S(s,{cors:{origin:'*'},pingTimeout:3e4,pingInterval:1e4,transports:['websocket','polling']}),U=new Map(),cl=n=>String(n||'').replace(/\D/g,''),vd=n=>n&&n.length>=8&&n.length<=15&&/^(0|62)?8\d{7,13}$/.test(n);
a.use(e.static('public'));
a.get('/health',(q,r)=>r.json({ok:1,up:process.uptime()}));
a.get('/users',(q,r)=>r.json([...U.keys()]));
io.on('connection',t=>{
  console.log('[+]',t.id);
  t.on('register',r=>{const n=cl(r);console.log('[REG]',t.id,'->',n);if(!vd(n))return t.emit('register-error','Nomor tidak valid (08xxx, 8-15 digit)');const o=U.get(n);if(o&&o!==t.id)io.to(o).emit('force-logout');U.set(n,t.id);t.noHp=n;console.log(' OK:',[...U.keys()].join(','));t.emit('registered',n)});
  const f=(ev,cb)=>t.on(ev,d=>{const i=U.get(cl(d.to));if(i)io.to(i).emit(cb,d)});
  t.on('call-user',d=>{const tg=cl(d.to),i=U.get(tg);console.log('[CALL]',t.noHp,'->',tg);if(!i)return t.emit('call-error',`Nomor ${tg} tidak online. Online: ${[...U.keys()].join(', ')||'kosong'}`);io.to(i).emit('incoming-call',{from:t.noHp})});
  f('accept-call','call-accepted');
  f('reject-call','call-rejected');
  f('end-call','call-ended');
  t.on('offer',d=>{const i=U.get(cl(d.to));if(i)io.to(i).emit('offer',{from:t.noHp,sdp:d.sdp})});
  t.on('answer',d=>{const i=U.get(cl(d.to));if(i)io.to(i).emit('answer',{sdp:d.sdp})});
  t.on('ice-candidate',d=>{const i=U.get(cl(d.to));if(i)io.to(i).emit('ice-candidate',{candidate:d.candidate})});
  t.on('unregister',()=>{if(t.noHp&&U.get(t.noHp)===t.id)U.delete(t.noHp)});
  t.on('disconnect',r=>{if(t.noHp&&U.get(t.noHp)===t.id)U.delete(t.noHp);console.log('[-]',t.id,r,'sisa:',[...U.keys()].join(','))});
});
const P=process.env.PORT||3e3;
s.listen(P,'0.0.0.0',()=>console.log('Server: http://localhost:'+P));
